"""Generate a SYNTHETIC haor duck-farming survey for practice and experimentation.

Every row is artificial, drawn from the data-generating process below. It is NOT real
data and must never be used for results, figures or publication. Effect sizes are
set loosely from the thesis's reported odds ratios so the exercises behave similarly.
"""
import numpy as np
import pandas as pd
from pathlib import Path

SEED, N = 42, 300
rng = np.random.default_rng(SEED)
sig = lambda x: 1 / (1 + np.exp(-x))

age = np.clip(rng.normal(37, 10, N).round(), 18, 63)
female = rng.random(N) < 0.727
edu_years = np.clip(rng.choice([0, 5, 8, 10, 12, 14], N, p=[.28, .33, .14, .15, .06, .04]) + rng.integers(-1, 2, N), 0, 16)
hh_size = np.clip(rng.normal(4.9, 1.5, N).round(), 2, 10)
land_dec = np.clip(rng.gamma(1.2, 70, N).round(), 0, 600)
experience = np.clip((age - 18) * rng.uniform(0.1, 0.5, N), 1, 30).round()
training = rng.random(N) < 0.29
credit = rng.random(N) < 0.46
group = rng.random(N) < 0.51
market_km = np.clip(rng.normal(4.8, 2.4, N), 0.5, 9).round(1)
flock = np.clip(rng.gamma(2.2, 20, N).round(), 8, 255)
system = rng.choice(["Free-range", "Semi-intensive", "Intensive"], N, p=[.56, .38, .06])

# adoption of at least one climate-smart practice (log-odds from stated assumptions)
logit = (0.3 + 1.0 * training + 0.8 * credit - 0.035 * (age - 37)
         + 0.1 * (edu_years - 6) / 3 + 0.12 * (hh_size - 5) - 0.05 * (market_km - 4.8))
adopt = rng.random(N) < sig(logit - 0.35)
n_practices = np.where(adopt, np.clip(1 + rng.poisson(1.9, N), 1, 6), 0)

# resilience outcomes: better with more practices, plus noise
mort = np.clip(24 - 4.2 * n_practices + rng.normal(0, 6, N), 1, 50).round(1)
flock_lost = np.clip(38 - 7 * n_practices + rng.normal(0, 10, N), 0, 90).round(1)
restore_wk = np.clip(19 - 3.2 * n_practices + rng.normal(0, 4, N), 2, 40).round(1)
income = np.clip(30000 + 6000 * n_practices + 350 * flock + rng.normal(0, 14000, N), 12000, 310000).round(-2)
wei = np.clip(rng.normal(3.0, 0.8, N), 0, 5).round(2)  # independent of adoption by design

df = pd.DataFrame({
    "sample_no": np.arange(1, N + 1), "is_synthetic": 1,
    "age": age.astype(int), "gender": np.where(female, "Female", "Male"),
    "education_years": edu_years.astype(int), "hh_size": hh_size.astype(int),
    "land_decimals": land_dec.astype(int), "experience_years": experience.astype(int),
    "farming_system": system, "flock_size": flock.astype(int), "market_distance_km": market_km,
    "extension_training": training.astype(int), "credit_access": credit.astype(int),
    "group_member": group.astype(int), "gross_income_bdt": income.astype(int),
    "csat_adopted": adopt.astype(int), "n_practices": n_practices,
    "flood_mortality_pct": mort, "flock_lost_pct": flock_lost,
    "restore_weeks": restore_wk, "wei_score": wei, "empowered": (wei >= 2.5).astype(int),
})
df["low_mortality"] = (df.flood_mortality_pct <= 15).astype(int)

out = Path(__file__).resolve().parents[1] / "data" / "synthetic"
out.mkdir(parents=True, exist_ok=True)
df.to_csv(out / "SYNTHETIC_duck_survey.csv", index=False)
(out / "README.md").write_text(
    "# SYNTHETIC data - not real\n\nGenerated by `scripts/make_synthetic_data.py` (seed 42). "
    "Artificial rows for learning pipelines (EDA, modelling, SHAP, the web form). "
    "Do not report results from it.\n\nTargets: `csat_adopted`, `low_mortality`, `empowered` "
    "(empowerment is independent of adoption by design).\n", encoding="utf-8")
print(df.shape, "adopt", round(df.csat_adopted.mean(), 3), "low_mort", round(df.low_mortality.mean(), 3),
      "female", round(female.mean(), 3))
